version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: adriel/crud-base-structure
    ports:
      - "3000:3000"
    environment:
      - PG_DB=crud
      - PG_USER=adriel
      - PG_PASSWORD=admin
      - PG_HOST=node_db
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=crud
      - POSTGRES_USER=adriel
      - POSTGRES_PASSWORD=admin
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}